services:
  valkey:
    image: valkey/valkey:8.0
    container_name: authentication-server-valkey
    restart: unless-stopped
    environment:
      VALKEY_PASSWORD: valkey_password
    command: >
      sh -c 'exec valkey-server --appendonly yes --requirepass "$$VALKEY_PASSWORD"'
    ports:
      - "6379:6379"
    volumes:
      - ./valkey_data:/data
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli -a \"$$VALKEY_PASSWORD\" ping | grep -q PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:valkey:6379:0:valkey_password
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    ports:
      - "8083:8081"
  demo-auth-server:
    build:
      context: ../demo-authentication-server
      dockerfile: Dockerfile
    container_name: demo-auth-server
    restart: unless-stopped
    environment:
      JAVA_OPTS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
      DEFAULT_CLIENT_SECRET: defaultsecret
      DEFAULT_USER_PASSWORD: password
    ports:
      - "8081:8081"
  demo-auth-resource:
    build:
      context: ../demo-auth-resource
      dockerfile: Dockerfile
    container_name: demo-auth-resource
    restart: unless-stopped
    environment:
      JAVA_OPTS: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
    ports:
      - "8082:8080"